### ISSUE TITLE
Question about the comments style.

### ISSUE THREAD

**Issue by leoheck** [whitequark/Sublime-S-Expressions#2]
Hello @whitequark, I am using this plugin for the first time and I have this question. 

I am using a tool called Kicad that is used to make PCBs, The next version of the tool is going to uses S-Expressions. It is currently being developed.

They are commenting out blocks with the "#" character but this plugin does not highlight these blocks as commnets. 
So, I have a question. Are they using the wrong way to comment on s-expressions or this plugin is not highlighting this type of comments but it should have been doing this?

Check this example:
![image](https://user-images.githubusercontent.com/1277920/109396636-4a20ca80-7911-11eb-9f5c-8b122b10c654.png)

**Comment by whitequark** [comment]
> Are they using the wrong way to comment on s-expressions or this plugin is not highlighting this type of comments but it should have been doing this?

Neither. There is no single concrete "S expression" syntax, and no single way to represent comments. I think you should copy the definitions in this plugin, rename it to something like "Kicad S Expressions" and alter the syntax definitions to match what Kicad does. (I am answering your question as someone who has used Kicad and is aware of the specific format it uses.)

**Comment by leoheck** [comment]
Cool. What do you think about adding this here? It is just a matter of marking as comment, lines that starts with #.

**Comment by whitequark** [comment]
I already explained in the previous comment that I don't think it's appropriate to extend this package to handle Kicad.

**Comment by leoheck** [comment]
Sure, I am not talking about Kicad. Kicad was just an example.
I am talking about comments that start with #

--
Leandro Heck

**Comment by leoheck** [comment]
For instance, 
Readme states that

```
Line comments
; hello;
```

It could be
```
Line comments
; hello;
# hello;
```
